### ISSUE TITLE
how to change subreddit to special one ?

### ISSUE THREAD

**Issue by todokku** [waishingwong1993/Reddit-video-generation#1]
hi wong ,
at the first , special thanks for your works ,
please tell me how to change subreddit to special one ?
finest regards

**Comment by waishingwong1993** [comment]
change the string variable subreddit_name to whichever subreddit you desired. 
1. Note, I am pulling from the "hot" section of reddit.  Check the file redditComment to change this.
2. And I am only pulling posts / comments with 1000 characters or less. I believe you should be able to change this after inspecting the files a bit.
